export declare const svgIcon: {
    add: string;
    del: string;
    addCircle: string;
    delCircle: string;
    modify: string;
    lockOpen: string;
    lockClose: string;
    print: string;
    export: string;
    import: string;
    argee: string;
    back: string;
    commit: string;
    reSend: string;
    reSet: string;
    summation: string;
    merge: string;
    download: string;
    setting: string;
    upload: string;
    archives: string;
    approval: string;
    notified: string;
};
export declare const iconColors: {
    primary: string;
    success: string;
    error: string;
    warning: string;
    info: string;
    default: string;
};
